global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: gateway
    static_configs:
      - targets: ['backend-gateway:9090']

  - job_name: ingester
    dns_sd_configs:
      - names: ['backend-ingester']
        type: A
        port: 9093
        refresh_interval: 15s

  - job_name: api
    static_configs:
      - targets: ['backend-api:9091']
